### ISSUE TITLE
게임 제출 횟수 개발 필요

### ISSUE THREAD

**Issue by nerdlyotter** [SanGyuk-Raccoon/toy-project#10]
game_count 변수와 while문을 통해 구현해보자 했으나 잘 되지 않음.
빠른 시일 내에 수정할 것임.

```
game_count = 0
while game_count > 10:
    ...
    game_count += 1
```

또한, 
'오류값을 입력했을 시 game_count에 포함을 시킬 것인가?' 라는 의문점이 생김.

**Comment by SanGyuk-Raccoon** [comment]
```
'오류값을 입력했을 시 game_count에 포함을 시킬 것인가?' 라는 의문점이 생김.
```
23.10.24 논의에서 포함시키지 않는 것으로 결정함.
https://github.com/SanGyuk-Raccoon/toy-project/wiki/Bulls-and-Cows

**Comment by otterbits** [comment]
'''
commit fd8405f1a64a5794547c06b64379f88739ecc5ef
'''

**Comment by nerdlyotter** [comment]
(https://github.com/SanGyuk-Raccoon/toy-project/commit/fd8405f1a64a5794547c06b64379f88739ecc5ef)

위의 commit으로 해결하였습니다.
감사합니다.
