### ISSUE TITLE
bulls and cows 추가 기능 도출

### ISSUE THREAD

**Issue by SanGyuk-Raccoon** [SanGyuk-Raccoon/toy-project#14]
실제 간단한 콘솔 게임으로 활용할 수 있도록 다양한 Scene이 추가되어야 합니다.

bulls-and-cows의 milestone을 고려하여 추가할 수 있는 기능을 Issue로 등록해주세요.

[예시]

- 타이틀
- play 화면
- 종료 & 재시작

[최소 요구사항]
(1) 게임 플레이
(2) retry or exit 선택

- 게임이 끝난다고 해서 프로그램이 종료되지 않도록 한다. (User의 선택에 따라 재시작/종료될 수 있도록 한다.)

[Extra]

- 게임 중 재시작 기능
- 랭킹 보드
- 그 외, 실현 가능한 모든 것에 대해 추가 가능

**Comment by nerdlyotter** [comment]
[게임 중 재시작 기능](https://github.com/SanGyuk-Raccoon/toy-project/issues/15)

[게임 결과창](https://github.com/SanGyuk-Raccoon/toy-project/issues/16)

[랭킹 보드](https://github.com/SanGyuk-Raccoon/toy-project/issues/17)

[게임 타이틀](https://github.com/SanGyuk-Raccoon/toy-project/issues/18)

[점수 계산](https://github.com/SanGyuk-Raccoon/toy-project/issues/19)

[플레이 시간 표시](https://github.com/SanGyuk-Raccoon/toy-project/issues/20)

[답안 표시창](https://github.com/SanGyuk-Raccoon/toy-project/issues/21)

[HOMERUN 추가](https://github.com/SanGyuk-Raccoon/toy-project/issues/22)
