### ISSUE TITLE
플레이 시간 표시

### ISSUE THREAD

**Issue by nerdlyotter** [SanGyuk-Raccoon/toy-project#20]
게임 시작 : y에 답하고 난 뒤부터 15분(900초)를 세아리는 시계를 구현

[답안 표시창](https://github.com/SanGyuk-Raccoon/toy-project/issues/21) 참고

- 위치 : 'enter the number' 질문 우측 상단
- 단위 : 15:00에서 00:00까지 점점 깎이는 형태로 표시

**Comment by SanGyuk-Raccoon** [comment]
난이도 문제로 포기
