### ISSUE TITLE
HOMERUN 추가

### ISSUE THREAD

**Issue by nerdlyotter** [SanGyuk-Raccoon/toy-project#22]
시도횟수 1번일 때(시작하자마자) 맞췄을 시,
+1000점 획득

- 'HOMERUN!'(빨주노초파남보로 1초마다 각각의 색깔변경)

**Comment by otterbits** [comment]
commit 960621fc18872bfa46cdd1eb811ac270954b4243

**Comment by nerdlyotter** [comment]
960621fc18872bfa46cdd1eb811ac270954b4243

해당 커밋으로 추가하였습니다.
