### ISSUE TITLE
git pull 시 발생하는 오류

### ISSUE THREAD

**Issue by nerdlyotter** [SanGyuk-Raccoon/toy-project#7]
git pull origin main 시 아래의 오류가 발생합니다.
fatal : Need to specify how to reconcile divergent branches.

**Comment by nerdlyotter** [comment]
https://velog.io/@eunddodi/git-pull-시-발생하는-warning-해결하기Need-to-specify-how-to-reconcile-divergent-branches
https://devum.tistory.com/77

위 두 사이트로 해결은 했으나 공유하고 싶어 issue는 닫지 않고 두겠습니다.

**Comment by SanGyuk-Raccoon** [comment]
ff로 설정바랍니다. 수고하셨습니다.
```
git config pull.ff only
```
