### ISSUE TITLE
함수 우선순위 정하기

### ISSUE THREAD

**Issue by nerdlyotter** [SanGyuk-Raccoon/toy-project#9]
Bulls and Cows 구현하면서
input의 오류를 잡아야 결과값을 출력하는 식으로 구현을 하고싶은데, 계속 오류값과 strike와 ball 값이 같이 출력되어 어려움을 겪었음.
ex) user_answer : 777 -> error문도 출력되면서 '0S 3B' 이런 식으로 결과값도 출력됨

**Comment by SanGyuk-Raccoon** [comment]
아래 commit으로 해결함.

https://github.com/SanGyuk-Raccoon/toy-project/pull/8/commits/6392746adab67907fb6e599f0718c0cf86378673
